<?php

use Illuminate\Database\Seeder;

class CiudadesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ciudades')->insert([
			['nombre' =>  'Leticia', 'departamento_id' => 1],
			['nombre' =>  'Puerto Nariño', 'departamento_id' => 1],
			['nombre' =>  'Abejorral', 'departamento_id' => 2],
			['nombre' =>  'Abriaquí', 'departamento_id' => 2],
			['nombre' =>  'Alejandria', 'departamento_id' => 2],
			['nombre' =>  'Amagá', 'departamento_id' => 2],
			['nombre' =>  'Amalfi', 'departamento_id' => 2],
			['nombre' =>  'Andes', 'departamento_id' => 2],
			['nombre' =>  'Angelópolis', 'departamento_id' => 2],
			['nombre' =>  'Angostura', 'departamento_id' => 2],
			['nombre' =>  'Anorí', 'departamento_id' => 2],
			['nombre' =>  'Anzá', 'departamento_id' => 2],
			['nombre' =>  'Apartadó', 'departamento_id' => 2],
			['nombre' =>  'Arboletes', 'departamento_id' => 2],
			['nombre' =>  'Argelia', 'departamento_id' => 2],
			['nombre' =>  'Armenia', 'departamento_id' => 2],
			['nombre' =>  'Barbosa', 'departamento_id' => 2],
			['nombre' =>  'Bello', 'departamento_id' => 2],
			['nombre' =>  'Belmira', 'departamento_id' => 2],
			['nombre' =>  'Betania', 'departamento_id' => 2],
			['nombre' =>  'Betulia', 'departamento_id' => 2],
			['nombre' =>  'Ciudad Bolívar', 'departamento_id' => 2],
			['nombre' =>  'Briceño', 'departamento_id' => 2],
			['nombre' =>  'Burítica', 'departamento_id' => 2],
			['nombre' =>  'Caicedo', 'departamento_id' => 2],
			['nombre' =>  'Caldas', 'departamento_id' => 2],
			['nombre' =>  'Campamento', 'departamento_id' => 2],
			['nombre' =>  'Caracolí', 'departamento_id' => 2],
			['nombre' =>  'Caramanta', 'departamento_id' => 2],
			['nombre' =>  'Carepa', 'departamento_id' => 2],
			['nombre' =>  'El Carmen de Viboral', 'departamento_id' => 2],
			['nombre' =>  'Carolina', 'departamento_id' => 2],
			['nombre' =>  'Caucasia', 'departamento_id' => 2],
			['nombre' =>  'Cañasgordas', 'departamento_id' => 2],
			['nombre' =>  'Chigorodó', 'departamento_id' => 2],
			['nombre' =>  'Cisneros', 'departamento_id' => 2],
			['nombre' =>  'Cocorná', 'departamento_id' => 2],
			['nombre' =>  'Concepción', 'departamento_id' => 2],
			['nombre' =>  'Concordia', 'departamento_id' => 2],
			['nombre' =>  'Copacabana', 'departamento_id' => 2],
			['nombre' =>  'Cáceres', 'departamento_id' => 2],
			['nombre' =>  'Dabeiba', 'departamento_id' => 2],
			['nombre' =>  'Don Matías', 'departamento_id' => 2],
			['nombre' =>  'Ebéjico', 'departamento_id' => 2],
			['nombre' =>  'El Bagre', 'departamento_id' => 2],
			['nombre' =>  'Entrerríos', 'departamento_id' => 2],
			['nombre' =>  'Envigado', 'departamento_id' => 2],
			['nombre' =>  'Fredonia', 'departamento_id' => 2],
			['nombre' =>  'Frontino', 'departamento_id' => 2],
			['nombre' =>  'Giraldo', 'departamento_id' => 2],
			['nombre' =>  'Girardota', 'departamento_id' => 2],
			['nombre' =>  'Granada', 'departamento_id' => 2],
			['nombre' =>  'Guadalupe', 'departamento_id' => 2],
			['nombre' =>  'Guarne', 'departamento_id' => 2],
			['nombre' =>  'Guatapé', 'departamento_id' => 2],
			['nombre' =>  'Gómez Plata', 'departamento_id' => 2],
			['nombre' =>  'Heliconia', 'departamento_id' => 2],
			['nombre' =>  'Hispania', 'departamento_id' => 2],
			['nombre' =>  'Itagüí', 'departamento_id' => 2],
			['nombre' =>  'Ituango', 'departamento_id' => 2],
			['nombre' =>  'Jardín', 'departamento_id' => 2],
			['nombre' =>  'Jericó', 'departamento_id' => 2],
			['nombre' =>  'La Ceja', 'departamento_id' => 2],
			['nombre' =>  'La Estrella', 'departamento_id' => 2],
			['nombre' =>  'La Pintada', 'departamento_id' => 2],
			['nombre' =>  'La Unión', 'departamento_id' => 2],
			['nombre' =>  'Liborina', 'departamento_id' => 2],
			['nombre' =>  'Maceo', 'departamento_id' => 2],
			['nombre' =>  'Marinilla', 'departamento_id' => 2],
			['nombre' =>  'Medellín', 'departamento_id' => 2],
			['nombre' =>  'Montebello', 'departamento_id' => 2],
			['nombre' =>  'Murindó', 'departamento_id' => 2],
			['nombre' =>  'Mutatá', 'departamento_id' => 2],
			['nombre' =>  'Nariño', 'departamento_id' => 2],
			['nombre' =>  'Nechí', 'departamento_id' => 2],
			['nombre' =>  'Necoclí', 'departamento_id' => 2],
			['nombre' =>  'Olaya', 'departamento_id' => 2],
			['nombre' =>  'Peque', 'departamento_id' => 2],
			['nombre' =>  'Peñol', 'departamento_id' => 2],
			['nombre' =>  'Pueblorrico', 'departamento_id' => 2],
			['nombre' =>  'Puerto Berrío', 'departamento_id' => 2],
			['nombre' =>  'Puerto Nare', 'departamento_id' => 2],
			['nombre' =>  'Puerto Triunfo', 'departamento_id' => 2],
			['nombre' =>  'Remedios', 'departamento_id' => 2],
			['nombre' =>  'Retiro', 'departamento_id' => 2],
			['nombre' =>  'Rionegro', 'departamento_id' => 2],
			['nombre' =>  'Sabanalarga', 'departamento_id' => 2],
			['nombre' =>  'Sabaneta', 'departamento_id' => 2],
			['nombre' =>  'Salgar', 'departamento_id' => 2],
			['nombre' =>  'San Andrés de Cuerquía', 'departamento_id' => 2],
			['nombre' =>  'San Carlos', 'departamento_id' => 2],
			['nombre' =>  'San Francisco', 'departamento_id' => 2],
			['nombre' =>  'San Jerónimo', 'departamento_id' => 2],
			['nombre' =>  'San José de la Montaña', 'departamento_id' => 2],
			['nombre' =>  'San Juan de Urabá', 'departamento_id' => 2],
			['nombre' =>  'San Luís', 'departamento_id' => 2],
			['nombre' =>  'San Pedro', 'departamento_id' => 2],
			['nombre' =>  'San Pedro de Urabá', 'departamento_id' => 2],
			['nombre' =>  'San Rafael', 'departamento_id' => 2],
			['nombre' =>  'San Roque', 'departamento_id' => 2],
			['nombre' =>  'San Vicente', 'departamento_id' => 2],
			['nombre' =>  'Santa Bárbara', 'departamento_id' => 2],
			['nombre' =>  'Santa Fé de Antioquia', 'departamento_id' => 2],
			['nombre' =>  'Santa Rosa de Osos', 'departamento_id' => 2],
			['nombre' =>  'Santo Domingo', 'departamento_id' => 2],
			['nombre' =>  'El Santuario', 'departamento_id' => 2],
			['nombre' =>  'Segovia', 'departamento_id' => 2],
			['nombre' =>  'Sonsón', 'departamento_id' => 2],
			['nombre' =>  'Sopetrán', 'departamento_id' => 2],
			['nombre' =>  'Tarazá', 'departamento_id' => 2],
			['nombre' =>  'Tarso', 'departamento_id' => 2],
			['nombre' =>  'Titiribí', 'departamento_id' => 2],
			['nombre' =>  'Toledo', 'departamento_id' => 2],
			['nombre' =>  'Turbo', 'departamento_id' => 2],
			['nombre' =>  'Támesis', 'departamento_id' => 2],
			['nombre' =>  'Uramita', 'departamento_id' => 2],
			['nombre' =>  'Urrao', 'departamento_id' => 2],
			['nombre' =>  'Valdivia', 'departamento_id' => 2],
			['nombre' =>  'Valparaiso', 'departamento_id' => 2],
			['nombre' =>  'Vegachí', 'departamento_id' => 2],
			['nombre' =>  'Venecia', 'departamento_id' => 2],
			['nombre' =>  'Vigía del Fuerte', 'departamento_id' => 2],
			['nombre' =>  'Yalí', 'departamento_id' => 2],
			['nombre' =>  'Yarumal', 'departamento_id' => 2],
			['nombre' =>  'Yolombó', 'departamento_id' => 2],
			['nombre' =>  'Yondó (Casabe)', 'departamento_id' => 2],
			['nombre' =>  'Zaragoza', 'departamento_id' => 2],
			['nombre' =>  'Arauca', 'departamento_id' => 3],
			['nombre' =>  'Arauquita', 'departamento_id' => 3],
			['nombre' =>  'Cravo Norte', 'departamento_id' => 3],
			['nombre' =>  'Fortúl', 'departamento_id' => 3],
			['nombre' =>  'Puerto Rondón', 'departamento_id' => 3],
			['nombre' =>  'Saravena', 'departamento_id' => 3],
			['nombre' =>  'Tame', 'departamento_id' => 3],
			['nombre' =>  'Baranoa', 'departamento_id' => 4],
			['nombre' =>  'Barranquilla', 'departamento_id' => 4],
			['nombre' =>  'Campo de la Cruz', 'departamento_id' => 4],
			['nombre' =>  'Candelaria', 'departamento_id' => 4],
			['nombre' =>  'Galapa', 'departamento_id' => 4],
			['nombre' =>  'Juan de Acosta', 'departamento_id' => 4],
			['nombre' =>  'Luruaco', 'departamento_id' => 4],
			['nombre' =>  'Malambo', 'departamento_id' => 4],
			['nombre' =>  'Manatí', 'departamento_id' => 4],
			['nombre' =>  'Palmar de Varela', 'departamento_id' => 4],
			['nombre' =>  'Piojo', 'departamento_id' => 4],
			['nombre' =>  'Polonuevo', 'departamento_id' => 4],
			['nombre' =>  'Ponedera', 'departamento_id' => 4],
			['nombre' =>  'Puerto Colombia', 'departamento_id' => 4],
			['nombre' =>  'Repelón', 'departamento_id' => 4],
			['nombre' =>  'Sabanagrande', 'departamento_id' => 4],
			['nombre' =>  'Sabanalarga', 'departamento_id' => 4],
			['nombre' =>  'Santa Lucía', 'departamento_id' => 4],
			['nombre' =>  'Santo Tomás', 'departamento_id' => 4],
			['nombre' =>  'Soledad', 'departamento_id' => 4],
			['nombre' =>  'Suan', 'departamento_id' => 4],
			['nombre' =>  'Tubará', 'departamento_id' => 4],
			['nombre' =>  'Usiacuri', 'departamento_id' => 4],
			['nombre' =>  'Achí', 'departamento_id' => 5],
			['nombre' =>  'Altos del Rosario', 'departamento_id' => 5],
			['nombre' =>  'Arenal', 'departamento_id' => 5],
			['nombre' =>  'Arjona', 'departamento_id' => 5],
			['nombre' =>  'Arroyohondo', 'departamento_id' => 5],
			['nombre' =>  'Barranco de Loba', 'departamento_id' => 5],
			['nombre' =>  'Calamar', 'departamento_id' => 5],
			['nombre' =>  'Cantagallo', 'departamento_id' => 5],
			['nombre' =>  'Cartagena', 'departamento_id' => 5],
			['nombre' =>  'Cicuco', 'departamento_id' => 5],
			['nombre' =>  'Clemencia', 'departamento_id' => 5],
			['nombre' =>  'Córdoba', 'departamento_id' => 5],
			['nombre' =>  'El Carmen de Bolívar', 'departamento_id' => 5],
			['nombre' =>  'El Guamo', 'departamento_id' => 5],
			['nombre' =>  'El Peñon', 'departamento_id' => 5],
			['nombre' =>  'Hatillo de Loba', 'departamento_id' => 5],
			['nombre' =>  'Magangué', 'departamento_id' => 5],
			['nombre' =>  'Mahates', 'departamento_id' => 5],
			['nombre' =>  'Margarita', 'departamento_id' => 5],
			['nombre' =>  'María la Baja', 'departamento_id' => 5],
			['nombre' =>  'Mompós', 'departamento_id' => 5],
			['nombre' =>  'Montecristo', 'departamento_id' => 5],
			['nombre' =>  'Morales', 'departamento_id' => 5],
			['nombre' =>  'Norosí', 'departamento_id' => 5],
			['nombre' =>  'Pinillos', 'departamento_id' => 5],
			['nombre' =>  'Regidor', 'departamento_id' => 5],
			['nombre' =>  'Río Viejo', 'departamento_id' => 5],
			['nombre' =>  'San Cristobal', 'departamento_id' => 5],
			['nombre' =>  'San Estanislao', 'departamento_id' => 5],
			['nombre' =>  'San Fernando', 'departamento_id' => 5],
			['nombre' =>  'San Jacinto', 'departamento_id' => 5],
			['nombre' =>  'San Jacinto del Cauca', 'departamento_id' => 5],
			['nombre' =>  'San Juan de Nepomuceno', 'departamento_id' => 5],
			['nombre' =>  'San Martín de Loba', 'departamento_id' => 5],
			['nombre' =>  'San Pablo', 'departamento_id' => 5],
			['nombre' =>  'Santa Catalina', 'departamento_id' => 5],
			['nombre' =>  'Santa Rosa ', 'departamento_id' => 5],
			['nombre' =>  'Santa Rosa del Sur', 'departamento_id' => 5],
			['nombre' =>  'Simití', 'departamento_id' => 5],
			['nombre' =>  'Soplaviento', 'departamento_id' => 5],
			['nombre' =>  'Talaigua Nuevo', 'departamento_id' => 5],
			['nombre' =>  'Tiquisio (Puerto Rico)', 'departamento_id' => 5],
			['nombre' =>  'Turbaco', 'departamento_id' => 5],
			['nombre' =>  'Turbaná', 'departamento_id' => 5],
			['nombre' =>  'Villanueva', 'departamento_id' => 5],
			['nombre' =>  'Zambrano', 'departamento_id' => 5],
			['nombre' =>  'Almeida', 'departamento_id' => 6],
			['nombre' =>  'Aquitania', 'departamento_id' => 6],
			['nombre' =>  'Arcabuco', 'departamento_id' => 6],
			['nombre' =>  'Belén', 'departamento_id' => 6],
			['nombre' =>  'Berbeo', 'departamento_id' => 6],
			['nombre' =>  'Beteitiva', 'departamento_id' => 6],
			['nombre' =>  'Boavita', 'departamento_id' => 6],
			['nombre' =>  'Boyacá', 'departamento_id' => 6],
			['nombre' =>  'Briceño', 'departamento_id' => 6],
			['nombre' =>  'Buenavista', 'departamento_id' => 6],
			['nombre' =>  'Busbanza', 'departamento_id' => 6],
			['nombre' =>  'Caldas', 'departamento_id' => 6],
			['nombre' =>  'Campohermoso', 'departamento_id' => 6],
			['nombre' =>  'Cerinza', 'departamento_id' => 6],
			['nombre' =>  'Chinavita', 'departamento_id' => 6],
			['nombre' =>  'Chiquinquirá', 'departamento_id' => 6],
			['nombre' =>  'Chiscas', 'departamento_id' => 6],
			['nombre' =>  'Chita', 'departamento_id' => 6],
			['nombre' =>  'Chitaraque', 'departamento_id' => 6],
			['nombre' =>  'Chivatá', 'departamento_id' => 6],
			['nombre' =>  'Chíquiza', 'departamento_id' => 6],
			['nombre' =>  'Chívor', 'departamento_id' => 6],
			['nombre' =>  'Ciénaga', 'departamento_id' => 6],
			['nombre' =>  'Coper', 'departamento_id' => 6],
			['nombre' =>  'Corrales', 'departamento_id' => 6],
			['nombre' =>  'Covarachía', 'departamento_id' => 6],
			['nombre' =>  'Cubará', 'departamento_id' => 6],
			['nombre' =>  'Cucaita', 'departamento_id' => 6],
			['nombre' =>  'Cuitiva', 'departamento_id' => 6],
			['nombre' =>  'Cómbita', 'departamento_id' => 6],
			['nombre' =>  'Duitama', 'departamento_id' => 6],
			['nombre' =>  'El Cocuy', 'departamento_id' => 6],
			['nombre' =>  'El Espino', 'departamento_id' => 6],
			['nombre' =>  'Firavitoba', 'departamento_id' => 6],
			['nombre' =>  'Floresta', 'departamento_id' => 6],
			['nombre' =>  'Gachantivá', 'departamento_id' => 6],
			['nombre' =>  'Garagoa', 'departamento_id' => 6],
			['nombre' =>  'Guacamayas', 'departamento_id' => 6],
			['nombre' =>  'Guateque', 'departamento_id' => 6],
			['nombre' =>  'Guayatá', 'departamento_id' => 6],
			['nombre' =>  'Güicán', 'departamento_id' => 6],
			['nombre' =>  'Gámeza', 'departamento_id' => 6],
			['nombre' =>  'Izá', 'departamento_id' => 6],
			['nombre' =>  'Jenesano', 'departamento_id' => 6],
			['nombre' =>  'Jericó', 'departamento_id' => 6],
			['nombre' =>  'La Capilla', 'departamento_id' => 6],
			['nombre' =>  'La Uvita', 'departamento_id' => 6],
			['nombre' =>  'La Victoria', 'departamento_id' => 6],
			['nombre' =>  'Labranzagrande', 'departamento_id' => 6],
			['nombre' =>  'Macanal', 'departamento_id' => 6],
			['nombre' =>  'Maripí', 'departamento_id' => 6],
			['nombre' =>  'Miraflores', 'departamento_id' => 6],
			['nombre' =>  'Mongua', 'departamento_id' => 6],
			['nombre' =>  'Monguí', 'departamento_id' => 6],
			['nombre' =>  'Moniquirá', 'departamento_id' => 6],
			['nombre' =>  'Motavita', 'departamento_id' => 6],
			['nombre' =>  'Muzo', 'departamento_id' => 6],
			['nombre' =>  'Nobsa', 'departamento_id' => 6],
			['nombre' =>  'Nuevo Colón', 'departamento_id' => 6],
			['nombre' =>  'Oicatá', 'departamento_id' => 6],
			['nombre' =>  'Otanche', 'departamento_id' => 6],
			['nombre' =>  'Pachavita', 'departamento_id' => 6],
			['nombre' =>  'Paipa', 'departamento_id' => 6],
			['nombre' =>  'Pajarito', 'departamento_id' => 6],
			['nombre' =>  'Panqueba', 'departamento_id' => 6],
			['nombre' =>  'Pauna', 'departamento_id' => 6],
			['nombre' =>  'Paya', 'departamento_id' => 6],
			['nombre' =>  'Paz de Río', 'departamento_id' => 6],
			['nombre' =>  'Pesca', 'departamento_id' => 6],
			['nombre' =>  'Pisba', 'departamento_id' => 6],
			['nombre' =>  'Puerto Boyacá', 'departamento_id' => 6],
			['nombre' =>  'Páez', 'departamento_id' => 6],
			['nombre' =>  'Quipama', 'departamento_id' => 6],
			['nombre' =>  'Ramiriquí', 'departamento_id' => 6],
			['nombre' =>  'Rondón', 'departamento_id' => 6],
			['nombre' =>  'Ráquira', 'departamento_id' => 6],
			['nombre' =>  'Saboyá', 'departamento_id' => 6],
			['nombre' =>  'Samacá', 'departamento_id' => 6],
			['nombre' =>  'San Eduardo', 'departamento_id' => 6],
			['nombre' =>  'San José de Pare', 'departamento_id' => 6],
			['nombre' =>  'San Luís de Gaceno', 'departamento_id' => 6],
			['nombre' =>  'San Mateo', 'departamento_id' => 6],
			['nombre' =>  'San Miguel de Sema', 'departamento_id' => 6],
			['nombre' =>  'San Pablo de Borbur', 'departamento_id' => 6],
			['nombre' =>  'Santa María', 'departamento_id' => 6],
			['nombre' =>  'Santa Rosa de Viterbo', 'departamento_id' => 6],
			['nombre' =>  'Santa Sofía', 'departamento_id' => 6],
			['nombre' =>  'Santana', 'departamento_id' => 6],
			['nombre' =>  'Sativanorte', 'departamento_id' => 6],
			['nombre' =>  'Sativasur', 'departamento_id' => 6],
			['nombre' =>  'Siachoque', 'departamento_id' => 6],
			['nombre' =>  'Soatá', 'departamento_id' => 6],
			['nombre' =>  'Socha', 'departamento_id' => 6],
			['nombre' =>  'Socotá', 'departamento_id' => 6],
			['nombre' =>  'Sogamoso', 'departamento_id' => 6],
			['nombre' =>  'Somondoco', 'departamento_id' => 6],
			['nombre' =>  'Sora', 'departamento_id' => 6],
			['nombre' =>  'Soracá', 'departamento_id' => 6],
			['nombre' =>  'Sotaquirá', 'departamento_id' => 6],
			['nombre' =>  'Susacón', 'departamento_id' => 6],
			['nombre' =>  'Sutamarchán', 'departamento_id' => 6],
			['nombre' =>  'Sutatenza', 'departamento_id' => 6],
			['nombre' =>  'Sáchica', 'departamento_id' => 6],
			['nombre' =>  'Tasco', 'departamento_id' => 6],
			['nombre' =>  'Tenza', 'departamento_id' => 6],
			['nombre' =>  'Tibaná', 'departamento_id' => 6],
			['nombre' =>  'Tibasosa', 'departamento_id' => 6],
			['nombre' =>  'Tinjacá', 'departamento_id' => 6],
			['nombre' =>  'Tipacoque', 'departamento_id' => 6],
			['nombre' =>  'Toca', 'departamento_id' => 6],
			['nombre' =>  'Togüí', 'departamento_id' => 6],
			['nombre' =>  'Topagá', 'departamento_id' => 6],
			['nombre' =>  'Tota', 'departamento_id' => 6],
			['nombre' =>  'Tunja', 'departamento_id' => 6],
			['nombre' =>  'Tunungua', 'departamento_id' => 6],
			['nombre' =>  'Turmequé', 'departamento_id' => 6],
			['nombre' =>  'Tuta', 'departamento_id' => 6],
			['nombre' =>  'Tutazá', 'departamento_id' => 6],
			['nombre' =>  'Ventaquemada', 'departamento_id' => 6],
			['nombre' =>  'Villa de Leyva', 'departamento_id' => 6],
			['nombre' =>  'Viracachá', 'departamento_id' => 6],
			['nombre' =>  'Zetaquirá', 'departamento_id' => 6],
			['nombre' =>  'Úmbita', 'departamento_id' => 6],
			['nombre' =>  'Aguadas', 'departamento_id' => 7],
			['nombre' =>  'Anserma', 'departamento_id' => 7],
			['nombre' =>  'Aranzazu', 'departamento_id' => 7],
			['nombre' =>  'Belalcázar', 'departamento_id' => 7],
			['nombre' =>  'Chinchiná', 'departamento_id' => 7],
			['nombre' =>  'Filadelfia', 'departamento_id' => 7],
			['nombre' =>  'La Dorada', 'departamento_id' => 7],
			['nombre' =>  'La Merced', 'departamento_id' => 7],
			['nombre' =>  'Victoria', 'departamento_id' => 7],
			['nombre' =>  'Manizales', 'departamento_id' => 7],
			['nombre' =>  'Manzanares', 'departamento_id' => 7],
			['nombre' =>  'Marmato', 'departamento_id' => 7],
			['nombre' =>  'Marquetalia', 'departamento_id' => 7],
			['nombre' =>  'Marulanda', 'departamento_id' => 7],
			['nombre' =>  'Neira', 'departamento_id' => 7],
			['nombre' =>  'Norcasia', 'departamento_id' => 7],
			['nombre' =>  'Palestina', 'departamento_id' => 7],
			['nombre' =>  'Pensilvania', 'departamento_id' => 7],
			['nombre' =>  'Pácora', 'departamento_id' => 7],
			['nombre' =>  'Risaralda', 'departamento_id' => 7],
			['nombre' =>  'Riosucio', 'departamento_id' => 7],
			['nombre' =>  'Salamina', 'departamento_id' => 7],
			['nombre' =>  'Samaná', 'departamento_id' => 7],
			['nombre' =>  'San José', 'departamento_id' => 7],
			['nombre' =>  'Supía', 'departamento_id' => 7],
			['nombre' =>  'Villamaría', 'departamento_id' => 7],
			['nombre' =>  'Viterbo', 'departamento_id' => 7],
			['nombre' =>  'Albania', 'departamento_id' => 8],
			['nombre' =>  'Belén de los Andaquíes', 'departamento_id' => 8],
			['nombre' =>  'Cartagena del Chairá', 'departamento_id' => 8],
			['nombre' =>  'Curillo', 'departamento_id' => 8],
			['nombre' =>  'El Doncello', 'departamento_id' => 8],
			['nombre' =>  'El Paujil', 'departamento_id' => 8],
			['nombre' =>  'Florencia', 'departamento_id' => 8],
			['nombre' =>  'La Montañita', 'departamento_id' => 8],
			['nombre' =>  'Milán', 'departamento_id' => 8],
			['nombre' =>  'Morelia', 'departamento_id' => 8],
			['nombre' =>  'Puerto Rico', 'departamento_id' => 8],
			['nombre' =>  'San José del Fragua', 'departamento_id' => 8],
			['nombre' =>  'San Vicente del Caguán', 'departamento_id' => 8],
			['nombre' =>  'Solano', 'departamento_id' => 8],
			['nombre' =>  'Solita', 'departamento_id' => 8],
			['nombre' =>  'Valparaiso', 'departamento_id' => 8],
			['nombre' =>  'Aguazul', 'departamento_id' => 9],
			['nombre' =>  'Chámeza', 'departamento_id' => 9],
			['nombre' =>  'Hato Corozal', 'departamento_id' => 9],
			['nombre' =>  'La Salina', 'departamento_id' => 9],
			['nombre' =>  'Maní', 'departamento_id' => 9],
			['nombre' =>  'Monterrey', 'departamento_id' => 9],
			['nombre' =>  'Nunchía', 'departamento_id' => 9],
			['nombre' =>  'Orocué', 'departamento_id' => 9],
			['nombre' =>  'Paz de Ariporo', 'departamento_id' => 9],
			['nombre' =>  'Pore', 'departamento_id' => 9],
			['nombre' =>  'Recetor', 'departamento_id' => 9],
			['nombre' =>  'Sabanalarga', 'departamento_id' => 9],
			['nombre' =>  'San Luís de Palenque', 'departamento_id' => 9],
			['nombre' =>  'Sácama', 'departamento_id' => 9],
			['nombre' =>  'Tauramena', 'departamento_id' => 9],
			['nombre' =>  'Trinidad', 'departamento_id' => 9],
			['nombre' =>  'Támara', 'departamento_id' => 9],
			['nombre' =>  'Villanueva', 'departamento_id' => 9],
			['nombre' =>  'Yopal', 'departamento_id' => 9],
			['nombre' =>  'Almaguer', 'departamento_id' => 10],
			['nombre' =>  'Argelia', 'departamento_id' => 10],
			['nombre' =>  'Balboa', 'departamento_id' => 10],
			['nombre' =>  'Bolívar', 'departamento_id' => 10],
			['nombre' =>  'Buenos Aires', 'departamento_id' => 10],
			['nombre' =>  'Cajibío', 'departamento_id' => 10],
			['nombre' =>  'Caldono', 'departamento_id' => 10],
			['nombre' =>  'Caloto', 'departamento_id' => 10],
			['nombre' =>  'Corinto', 'departamento_id' => 10],
			['nombre' =>  'El Tambo', 'departamento_id' => 10],
			['nombre' =>  'Florencia', 'departamento_id' => 10],
			['nombre' =>  'Guachené', 'departamento_id' => 10],
			['nombre' =>  'Guapí', 'departamento_id' => 10],
			['nombre' =>  'Inzá', 'departamento_id' => 10],
			['nombre' =>  'Jambaló', 'departamento_id' => 10],
			['nombre' =>  'La Sierra', 'departamento_id' => 10],
			['nombre' =>  'La Vega', 'departamento_id' => 10],
			['nombre' =>  'López (Micay)', 'departamento_id' => 10],
			['nombre' =>  'Mercaderes', 'departamento_id' => 10],
			['nombre' =>  'Miranda', 'departamento_id' => 10],
			['nombre' =>  'Morales', 'departamento_id' => 10],
			['nombre' =>  'Padilla', 'departamento_id' => 10],
			['nombre' =>  'Patía (El Bordo)', 'departamento_id' => 10],
			['nombre' =>  'Piamonte', 'departamento_id' => 10],
			['nombre' =>  'Piendamó', 'departamento_id' => 10],
			['nombre' =>  'Popayán', 'departamento_id' => 10],
			['nombre' =>  'Puerto Tejada', 'departamento_id' => 10],
			['nombre' =>  'Puracé (Coconuco)', 'departamento_id' => 10],
			['nombre' =>  'Páez (Belalcazar)', 'departamento_id' => 10],
			['nombre' =>  'Rosas', 'departamento_id' => 10],
			['nombre' =>  'San Sebastián', 'departamento_id' => 10],
			['nombre' =>  'Santa Rosa', 'departamento_id' => 10],
			['nombre' =>  'Santander de Quilichao', 'departamento_id' => 10],
			['nombre' =>  'Silvia', 'departamento_id' => 10],
			['nombre' =>  'Sotara (Paispamba)', 'departamento_id' => 10],
			['nombre' =>  'Sucre', 'departamento_id' => 10],
			['nombre' =>  'Suárez', 'departamento_id' => 10],
			['nombre' =>  'Timbiquí', 'departamento_id' => 10],
			['nombre' =>  'Timbío', 'departamento_id' => 10],
			['nombre' =>  'Toribío', 'departamento_id' => 10],
			['nombre' =>  'Totoró', 'departamento_id' => 10],
			['nombre' =>  'Villa Rica', 'departamento_id' => 10],
			['nombre' =>  'Aguachica', 'departamento_id' => 11],
			['nombre' =>  'Agustín Codazzi', 'departamento_id' => 11],
			['nombre' =>  'Astrea', 'departamento_id' => 11],
			['nombre' =>  'Becerríl', 'departamento_id' => 11],
			['nombre' =>  'Bosconia', 'departamento_id' => 11],
			['nombre' =>  'Chimichagua', 'departamento_id' => 11],
			['nombre' =>  'Chiriguaná', 'departamento_id' => 11],
			['nombre' =>  'Curumaní', 'departamento_id' => 11],
			['nombre' =>  'El Copey', 'departamento_id' => 11],
			['nombre' =>  'El Paso', 'departamento_id' => 11],
			['nombre' =>  'Gamarra', 'departamento_id' => 11],
			['nombre' =>  'Gonzalez', 'departamento_id' => 11],
			['nombre' =>  'La Gloria', 'departamento_id' => 11],
			['nombre' =>  'La Jagua de Ibirico', 'departamento_id' => 11],
			['nombre' =>  'La Paz (Robles)', 'departamento_id' => 11],
			['nombre' =>  'Manaure Balcón del Cesar', 'departamento_id' => 11],
			['nombre' =>  'Pailitas', 'departamento_id' => 11],
			['nombre' =>  'Pelaya', 'departamento_id' => 11],
			['nombre' =>  'Pueblo Bello', 'departamento_id' => 11],
			['nombre' =>  'Río de oro', 'departamento_id' => 11],
			['nombre' =>  'San Alberto', 'departamento_id' => 11],
			['nombre' =>  'San Diego', 'departamento_id' => 11],
			['nombre' =>  'San Martín', 'departamento_id' => 11],
			['nombre' =>  'Tamalameque', 'departamento_id' => 11],
			['nombre' =>  'Valledupar', 'departamento_id' => 11],
			['nombre' =>  'Acandí', 'departamento_id' => 12],
			['nombre' =>  'Alto Baudó (Pie de Pato)', 'departamento_id' => 12],
			['nombre' =>  'Atrato (Yuto)', 'departamento_id' => 12],
			['nombre' =>  'Bagadó', 'departamento_id' => 12],
			['nombre' =>  'Bahía Solano (Mútis)', 'departamento_id' => 12],
			['nombre' =>  'Bajo Baudó (Pizarro)', 'departamento_id' => 12],
			['nombre' =>  'Belén de Bajirá', 'departamento_id' => 12],
			['nombre' =>  'Bojayá (Bellavista)', 'departamento_id' => 12],
			['nombre' =>  'El Cantón de San Pablo', 'departamento_id' => 12],
			['nombre' =>  'Carmen del Darién (CURBARADÓ)', 'departamento_id' => 12],
			['nombre' =>  'Condoto', 'departamento_id' => 12],
			['nombre' =>  'Cértegui', 'departamento_id' => 12],
			['nombre' =>  'El Carmen de Atrato', 'departamento_id' => 12],
			['nombre' =>  'Istmina', 'departamento_id' => 12],
			['nombre' =>  'Juradó', 'departamento_id' => 12],
			['nombre' =>  'Lloró', 'departamento_id' => 12],
			['nombre' =>  'Medio Atrato', 'departamento_id' => 12],
			['nombre' =>  'Medio Baudó', 'departamento_id' => 12],
			['nombre' =>  'Medio San Juan (ANDAGOYA)', 'departamento_id' => 12],
			['nombre' =>  'Novita', 'departamento_id' => 12],
			['nombre' =>  'Nuquí', 'departamento_id' => 12],
			['nombre' =>  'Quibdó', 'departamento_id' => 12],
			['nombre' =>  'Río Iró', 'departamento_id' => 12],
			['nombre' =>  'Río Quito', 'departamento_id' => 12],
			['nombre' =>  'Riosucio', 'departamento_id' => 12],
			['nombre' =>  'San José del Palmar', 'departamento_id' => 12],
			['nombre' =>  'Sipí', 'departamento_id' => 12],
			['nombre' =>  'Tadó', 'departamento_id' => 12],
			['nombre' =>  'Unguía', 'departamento_id' => 12],
			['nombre' =>  'Unión Panamericana (ÁNIMAS)', 'departamento_id' => 12],
			['nombre' =>  'Ayapel', 'departamento_id' => 13],
			['nombre' =>  'Buenavista', 'departamento_id' => 13],
			['nombre' =>  'Canalete', 'departamento_id' => 13],
			['nombre' =>  'Cereté', 'departamento_id' => 13],
			['nombre' =>  'Chimá', 'departamento_id' => 13],
			['nombre' =>  'Chinú', 'departamento_id' => 13],
			['nombre' =>  'Ciénaga de Oro', 'departamento_id' => 13],
			['nombre' =>  'Cotorra', 'departamento_id' => 13],
			['nombre' =>  'La Apartada y La Frontera', 'departamento_id' => 13],
			['nombre' =>  'Lorica', 'departamento_id' => 13],
			['nombre' =>  'Los Córdobas', 'departamento_id' => 13],
			['nombre' =>  'Momil', 'departamento_id' => 13],
			['nombre' =>  'Montelíbano', 'departamento_id' => 13],
			['nombre' =>  'Monteria', 'departamento_id' => 13],
			['nombre' =>  'Moñitos', 'departamento_id' => 13],
			['nombre' =>  'Planeta Rica', 'departamento_id' => 13],
			['nombre' =>  'Pueblo Nuevo', 'departamento_id' => 13],
			['nombre' =>  'Puerto Escondido', 'departamento_id' => 13],
			['nombre' =>  'Puerto Libertador', 'departamento_id' => 13],
			['nombre' =>  'Purísima', 'departamento_id' => 13],
			['nombre' =>  'Sahagún', 'departamento_id' => 13],
			['nombre' =>  'San Andrés de Sotavento', 'departamento_id' => 13],
			['nombre' =>  'San Antero', 'departamento_id' => 13],
			['nombre' =>  'San Bernardo del Viento', 'departamento_id' => 13],
			['nombre' =>  'San Carlos', 'departamento_id' => 13],
			['nombre' =>  'San José de Uré', 'departamento_id' => 13],
			['nombre' =>  'San Pelayo', 'departamento_id' => 13],
			['nombre' =>  'Tierralta', 'departamento_id' => 13],
			['nombre' =>  'Tuchín', 'departamento_id' => 13],
			['nombre' =>  'Valencia', 'departamento_id' => 13],
			['nombre' =>  'Agua de Dios', 'departamento_id' => 14],
			['nombre' =>  'Albán', 'departamento_id' => 14],
			['nombre' =>  'Anapoima', 'departamento_id' => 14],
			['nombre' =>  'Anolaima', 'departamento_id' => 14],
			['nombre' =>  'Apulo', 'departamento_id' => 14],
			['nombre' =>  'Arbeláez', 'departamento_id' => 14],
			['nombre' =>  'Beltrán', 'departamento_id' => 14],
			['nombre' =>  'Bituima', 'departamento_id' => 14],
			['nombre' =>  'Bogotá D.C.', 'departamento_id' => 14],
			['nombre' =>  'Bojacá', 'departamento_id' => 14],
			['nombre' =>  'Cabrera', 'departamento_id' => 14],
			['nombre' =>  'Cachipay', 'departamento_id' => 14],
			['nombre' =>  'Cajicá', 'departamento_id' => 14],
			['nombre' =>  'Caparrapí', 'departamento_id' => 14],
			['nombre' =>  'Carmen de Carupa', 'departamento_id' => 14],
			['nombre' =>  'Chaguaní', 'departamento_id' => 14],
			['nombre' =>  'Chipaque', 'departamento_id' => 14],
			['nombre' =>  'Choachí', 'departamento_id' => 14],
			['nombre' =>  'Chocontá', 'departamento_id' => 14],
			['nombre' =>  'Chía', 'departamento_id' => 14],
			['nombre' =>  'Cogua', 'departamento_id' => 14],
			['nombre' =>  'Cota', 'departamento_id' => 14],
			['nombre' =>  'Cucunubá', 'departamento_id' => 14],
			['nombre' =>  'Cáqueza', 'departamento_id' => 14],
			['nombre' =>  'El Colegio', 'departamento_id' => 14],
			['nombre' =>  'El Peñón', 'departamento_id' => 14],
			['nombre' =>  'El Rosal', 'departamento_id' => 14],
			['nombre' =>  'Facatativá', 'departamento_id' => 14],
			['nombre' =>  'Fosca', 'departamento_id' => 14],
			['nombre' =>  'Funza', 'departamento_id' => 14],
			['nombre' =>  'Fusagasugá', 'departamento_id' => 14],
			['nombre' =>  'Fómeque', 'departamento_id' => 14],
			['nombre' =>  'Fúquene', 'departamento_id' => 14],
			['nombre' =>  'Gachalá', 'departamento_id' => 14],
			['nombre' =>  'Gachancipá', 'departamento_id' => 14],
			['nombre' =>  'Gachetá', 'departamento_id' => 14],
			['nombre' =>  'Gama', 'departamento_id' => 14],
			['nombre' =>  'Girardot', 'departamento_id' => 14],
			['nombre' =>  'Granada', 'departamento_id' => 14],
			['nombre' =>  'Guachetá', 'departamento_id' => 14],
			['nombre' =>  'Guaduas', 'departamento_id' => 14],
			['nombre' =>  'Guasca', 'departamento_id' => 14],
			['nombre' =>  'Guataquí', 'departamento_id' => 14],
			['nombre' =>  'Guatavita', 'departamento_id' => 14],
			['nombre' =>  'Guayabal de Siquima', 'departamento_id' => 14],
			['nombre' =>  'Guayabetal', 'departamento_id' => 14],
			['nombre' =>  'Gutiérrez', 'departamento_id' => 14],
			['nombre' =>  'Jerusalén', 'departamento_id' => 14],
			['nombre' =>  'Junín', 'departamento_id' => 14],
			['nombre' =>  'La Calera', 'departamento_id' => 14],
			['nombre' =>  'La Mesa', 'departamento_id' => 14],
			['nombre' =>  'La Palma', 'departamento_id' => 14],
			['nombre' =>  'La Peña', 'departamento_id' => 14],
			['nombre' =>  'La Vega', 'departamento_id' => 14],
			['nombre' =>  'Lenguazaque', 'departamento_id' => 14],
			['nombre' =>  'Machetá', 'departamento_id' => 14],
			['nombre' =>  'Madrid', 'departamento_id' => 14],
			['nombre' =>  'Manta', 'departamento_id' => 14],
			['nombre' =>  'Medina', 'departamento_id' => 14],
			['nombre' =>  'Mosquera', 'departamento_id' => 14],
			['nombre' =>  'Nariño', 'departamento_id' => 14],
			['nombre' =>  'Nemocón', 'departamento_id' => 14],
			['nombre' =>  'Nilo', 'departamento_id' => 14],
			['nombre' =>  'Nimaima', 'departamento_id' => 14],
			['nombre' =>  'Nocaima', 'departamento_id' => 14],
			['nombre' =>  'Pacho', 'departamento_id' => 14],
			['nombre' =>  'Paime', 'departamento_id' => 14],
			['nombre' =>  'Pandi', 'departamento_id' => 14],
			['nombre' =>  'Paratebueno', 'departamento_id' => 14],
			['nombre' =>  'Pasca', 'departamento_id' => 14],
			['nombre' =>  'Puerto Salgar', 'departamento_id' => 14],
			['nombre' =>  'Pulí', 'departamento_id' => 14],
			['nombre' =>  'Quebradanegra', 'departamento_id' => 14],
			['nombre' =>  'Quetame', 'departamento_id' => 14],
			['nombre' =>  'Quipile', 'departamento_id' => 14],
			['nombre' =>  'Ricaurte', 'departamento_id' => 14],
			['nombre' =>  'San Antonio de Tequendama', 'departamento_id' => 14],
			['nombre' =>  'San Bernardo', 'departamento_id' => 14],
			['nombre' =>  'San Cayetano', 'departamento_id' => 14],
			['nombre' =>  'San Francisco', 'departamento_id' => 14],
			['nombre' =>  'San Juan de Río Seco', 'departamento_id' => 14],
			['nombre' =>  'Sasaima', 'departamento_id' => 14],
			['nombre' =>  'Sesquilé', 'departamento_id' => 14],
			['nombre' =>  'Sibaté', 'departamento_id' => 14],
			['nombre' =>  'Silvania', 'departamento_id' => 14],
			['nombre' =>  'Simijaca', 'departamento_id' => 14],
			['nombre' =>  'Soacha', 'departamento_id' => 14],
			['nombre' =>  'Sopó', 'departamento_id' => 14],
			['nombre' =>  'Subachoque', 'departamento_id' => 14],
			['nombre' =>  'Suesca', 'departamento_id' => 14],
			['nombre' =>  'Supatá', 'departamento_id' => 14],
			['nombre' =>  'Susa', 'departamento_id' => 14],
			['nombre' =>  'Sutatausa', 'departamento_id' => 14],
			['nombre' =>  'Tabio', 'departamento_id' => 14],
			['nombre' =>  'Tausa', 'departamento_id' => 14],
			['nombre' =>  'Tena', 'departamento_id' => 14],
			['nombre' =>  'Tenjo', 'departamento_id' => 14],
			['nombre' =>  'Tibacuy', 'departamento_id' => 14],
			['nombre' =>  'Tibirita', 'departamento_id' => 14],
			['nombre' =>  'Tocaima', 'departamento_id' => 14],
			['nombre' =>  'Tocancipá', 'departamento_id' => 14],
			['nombre' =>  'Topaipí', 'departamento_id' => 14],
			['nombre' =>  'Ubalá', 'departamento_id' => 14],
			['nombre' =>  'Ubaque', 'departamento_id' => 14],
			['nombre' =>  'Villa de San Diego de Ubaté', 'departamento_id' => 14],
			['nombre' =>  'Une', 'departamento_id' => 14],
			['nombre' =>  'Venecia (Ospina Pérez)', 'departamento_id' => 14],
			['nombre' =>  'Vergara', 'departamento_id' => 14],
			['nombre' =>  'Viani', 'departamento_id' => 14],
			['nombre' =>  'Villagómez', 'departamento_id' => 14],
			['nombre' =>  'Villapinzón', 'departamento_id' => 14],
			['nombre' =>  'Villeta', 'departamento_id' => 14],
			['nombre' =>  'Viotá', 'departamento_id' => 14],
			['nombre' =>  'Yacopí', 'departamento_id' => 14],
			['nombre' =>  'Zipacón', 'departamento_id' => 14],
			['nombre' =>  'Zipaquirá', 'departamento_id' => 14],
			['nombre' =>  'Útica', 'departamento_id' => 14],
			['nombre' =>  'Inírida', 'departamento_id' => 15],
			['nombre' =>  'Calamar', 'departamento_id' => 16],
			['nombre' =>  'El Retorno', 'departamento_id' => 16],
			['nombre' =>  'Miraflores', 'departamento_id' => 16],
			['nombre' =>  'San José del Guaviare', 'departamento_id' => 16],
			['nombre' =>  'Acevedo', 'departamento_id' => 17],
			['nombre' =>  'Agrado', 'departamento_id' => 17],
			['nombre' =>  'Aipe', 'departamento_id' => 17],
			['nombre' =>  'Algeciras', 'departamento_id' => 17],
			['nombre' =>  'Altamira', 'departamento_id' => 17],
			['nombre' =>  'Baraya', 'departamento_id' => 17],
			['nombre' =>  'Campoalegre', 'departamento_id' => 17],
			['nombre' =>  'Colombia', 'departamento_id' => 17],
			['nombre' =>  'Elías', 'departamento_id' => 17],
			['nombre' =>  'Garzón', 'departamento_id' => 17],
			['nombre' =>  'Gigante', 'departamento_id' => 17],
			['nombre' =>  'Guadalupe', 'departamento_id' => 17],
			['nombre' =>  'Hobo', 'departamento_id' => 17],
			['nombre' =>  'Isnos', 'departamento_id' => 17],
			['nombre' =>  'La Argentina', 'departamento_id' => 17],
			['nombre' =>  'La Plata', 'departamento_id' => 17],
			['nombre' =>  'Neiva', 'departamento_id' => 17],
			['nombre' =>  'Nátaga', 'departamento_id' => 17],
			['nombre' =>  'Oporapa', 'departamento_id' => 17],
			['nombre' =>  'Paicol', 'departamento_id' => 17],
			['nombre' =>  'Palermo', 'departamento_id' => 17],
			['nombre' =>  'Palestina', 'departamento_id' => 17],
			['nombre' =>  'Pital', 'departamento_id' => 17],
			['nombre' =>  'Pitalito', 'departamento_id' => 17],
			['nombre' =>  'Rivera', 'departamento_id' => 17],
			['nombre' =>  'Saladoblanco', 'departamento_id' => 17],
			['nombre' =>  'San Agustín', 'departamento_id' => 17],
			['nombre' =>  'Santa María', 'departamento_id' => 17],
			['nombre' =>  'Suaza', 'departamento_id' => 17],
			['nombre' =>  'Tarqui', 'departamento_id' => 17],
			['nombre' =>  'Tello', 'departamento_id' => 17],
			['nombre' =>  'Teruel', 'departamento_id' => 17],
			['nombre' =>  'Tesalia', 'departamento_id' => 17],
			['nombre' =>  'Timaná', 'departamento_id' => 17],
			['nombre' =>  'Villavieja', 'departamento_id' => 17],
			['nombre' =>  'Yaguará', 'departamento_id' => 17],
			['nombre' =>  'Íquira', 'departamento_id' => 17],
			['nombre' =>  'Albania', 'departamento_id' => 18],
			['nombre' =>  'Barrancas', 'departamento_id' => 18],
			['nombre' =>  'Dibulla', 'departamento_id' => 18],
			['nombre' =>  'Distracción', 'departamento_id' => 18],
			['nombre' =>  'El Molino', 'departamento_id' => 18],
			['nombre' =>  'Fonseca', 'departamento_id' => 18],
			['nombre' =>  'Hatonuevo', 'departamento_id' => 18],
			['nombre' =>  'La Jagua del Pilar', 'departamento_id' => 18],
			['nombre' =>  'Maicao', 'departamento_id' => 18],
			['nombre' =>  'Manaure', 'departamento_id' => 18],
			['nombre' =>  'Riohacha', 'departamento_id' => 18],
			['nombre' =>  'San Juan del Cesar', 'departamento_id' => 18],
			['nombre' =>  'Uribia', 'departamento_id' => 18],
			['nombre' =>  'Urumita', 'departamento_id' => 18],
			['nombre' =>  'Villanueva', 'departamento_id' => 18],
			['nombre' =>  'Algarrobo', 'departamento_id' => 19],
			['nombre' =>  'Aracataca', 'departamento_id' => 19],
			['nombre' =>  'Ariguaní (El Difícil)', 'departamento_id' => 19],
			['nombre' =>  'Cerro San Antonio', 'departamento_id' => 19],
			['nombre' =>  'Chibolo', 'departamento_id' => 19],
			['nombre' =>  'Ciénaga', 'departamento_id' => 19],
			['nombre' =>  'Concordia', 'departamento_id' => 19],
			['nombre' =>  'El Banco', 'departamento_id' => 19],
			['nombre' =>  'El Piñon', 'departamento_id' => 19],
			['nombre' =>  'El Retén', 'departamento_id' => 19],
			['nombre' =>  'Fundación', 'departamento_id' => 19],
			['nombre' =>  'Guamal', 'departamento_id' => 19],
			['nombre' =>  'Nueva Granada', 'departamento_id' => 19],
			['nombre' =>  'Pedraza', 'departamento_id' => 19],
			['nombre' =>  'Pijiño', 'departamento_id' => 19],
			['nombre' =>  'Pivijay', 'departamento_id' => 19],
			['nombre' =>  'Plato', 'departamento_id' => 19],
			['nombre' =>  'Puebloviejo', 'departamento_id' => 19],
			['nombre' =>  'Remolino', 'departamento_id' => 19],
			['nombre' =>  'Sabanas de San Angel (SAN ANGEL)', 'departamento_id' => 19],
			['nombre' =>  'Salamina', 'departamento_id' => 19],
			['nombre' =>  'San Sebastián de Buenavista', 'departamento_id' => 19],
			['nombre' =>  'San Zenón', 'departamento_id' => 19],
			['nombre' =>  'Santa Ana', 'departamento_id' => 19],
			['nombre' =>  'Santa Bárbara de Pinto', 'departamento_id' => 19],
			['nombre' =>  'Santa Marta', 'departamento_id' => 19],
			['nombre' =>  'Sitionuevo', 'departamento_id' => 19],
			['nombre' =>  'Tenerife', 'departamento_id' => 19],
			['nombre' =>  'Zapayán (PUNTA DE PIEDRAS)', 'departamento_id' => 19],
			['nombre' =>  'Zona Bananera (PRADO - SEVILLA)', 'departamento_id' => 19],
			['nombre' =>  'Acacías', 'departamento_id' => 20],
			['nombre' =>  'Barranca de Upía', 'departamento_id' => 20],
			['nombre' =>  'Cabuyaro', 'departamento_id' => 20],
			['nombre' =>  'Castilla la Nueva', 'departamento_id' => 20],
			['nombre' =>  'Cubarral', 'departamento_id' => 20],
			['nombre' =>  'Cumaral', 'departamento_id' => 20],
			['nombre' =>  'El Calvario', 'departamento_id' => 20],
			['nombre' =>  'El Castillo', 'departamento_id' => 20],
			['nombre' =>  'El Dorado', 'departamento_id' => 20],
			['nombre' =>  'Fuente de Oro', 'departamento_id' => 20],
			['nombre' =>  'Granada', 'departamento_id' => 20],
			['nombre' =>  'Guamal', 'departamento_id' => 20],
			['nombre' =>  'La Macarena', 'departamento_id' => 20],
			['nombre' =>  'Lejanías', 'departamento_id' => 20],
			['nombre' =>  'Mapiripan', 'departamento_id' => 20],
			['nombre' =>  'Mesetas', 'departamento_id' => 20],
			['nombre' =>  'Puerto Concordia', 'departamento_id' => 20],
			['nombre' =>  'Puerto Gaitán', 'departamento_id' => 20],
			['nombre' =>  'Puerto Lleras', 'departamento_id' => 20],
			['nombre' =>  'Puerto López', 'departamento_id' => 20],
			['nombre' =>  'Puerto Rico', 'departamento_id' => 20],
			['nombre' =>  'Restrepo', 'departamento_id' => 20],
			['nombre' =>  'San Carlos de Guaroa', 'departamento_id' => 20],
			['nombre' =>  'San Juan de Arama', 'departamento_id' => 20],
			['nombre' =>  'San Juanito', 'departamento_id' => 20],
			['nombre' =>  'San Martín', 'departamento_id' => 20],
			['nombre' =>  'Uribe', 'departamento_id' => 20],
			['nombre' =>  'Villavicencio', 'departamento_id' => 20],
			['nombre' =>  'Vista Hermosa', 'departamento_id' => 20],
			['nombre' =>  'Albán (San José)', 'departamento_id' => 21],
			['nombre' =>  'Aldana', 'departamento_id' => 21],
			['nombre' =>  'Ancuya', 'departamento_id' => 21],
			['nombre' =>  'Arboleda (Berruecos)', 'departamento_id' => 21],
			['nombre' =>  'Barbacoas', 'departamento_id' => 21],
			['nombre' =>  'Belén', 'departamento_id' => 21],
			['nombre' =>  'Buesaco', 'departamento_id' => 21],
			['nombre' =>  'Chachagüí', 'departamento_id' => 21],
			['nombre' =>  'Colón (Génova)', 'departamento_id' => 21],
			['nombre' =>  'Consaca', 'departamento_id' => 21],
			['nombre' =>  'Contadero', 'departamento_id' => 21],
			['nombre' =>  'Cuaspud (Carlosama)', 'departamento_id' => 21],
			['nombre' =>  'Cumbal', 'departamento_id' => 21],
			['nombre' =>  'Cumbitara', 'departamento_id' => 21],
			['nombre' =>  'Córdoba', 'departamento_id' => 21],
			['nombre' =>  'El Charco', 'departamento_id' => 21],
			['nombre' =>  'El Peñol', 'departamento_id' => 21],
			['nombre' =>  'El Rosario', 'departamento_id' => 21],
			['nombre' =>  'El Tablón de Gómez', 'departamento_id' => 21],
			['nombre' =>  'El Tambo', 'departamento_id' => 21],
			['nombre' =>  'Francisco Pizarro', 'departamento_id' => 21],
			['nombre' =>  'Funes', 'departamento_id' => 21],
			['nombre' =>  'Guachavés', 'departamento_id' => 21],
			['nombre' =>  'Guachucal', 'departamento_id' => 21],
			['nombre' =>  'Guaitarilla', 'departamento_id' => 21],
			['nombre' =>  'Gualmatán', 'departamento_id' => 21],
			['nombre' =>  'Iles', 'departamento_id' => 21],
			['nombre' =>  'Imúes', 'departamento_id' => 21],
			['nombre' =>  'Ipiales', 'departamento_id' => 21],
			['nombre' =>  'La Cruz', 'departamento_id' => 21],
			['nombre' =>  'La Florida', 'departamento_id' => 21],
			['nombre' =>  'La Llanada', 'departamento_id' => 21],
			['nombre' =>  'La Tola', 'departamento_id' => 21],
			['nombre' =>  'La Unión', 'departamento_id' => 21],
			['nombre' =>  'Leiva', 'departamento_id' => 21],
			['nombre' =>  'Linares', 'departamento_id' => 21],
			['nombre' =>  'Magüi (Payán)', 'departamento_id' => 21],
			['nombre' =>  'Mallama (Piedrancha)', 'departamento_id' => 21],
			['nombre' =>  'Mosquera', 'departamento_id' => 21],
			['nombre' =>  'Nariño', 'departamento_id' => 21],
			['nombre' =>  'Olaya Herrera', 'departamento_id' => 21],
			['nombre' =>  'Ospina', 'departamento_id' => 21],
			['nombre' =>  'Policarpa', 'departamento_id' => 21],
			['nombre' =>  'Potosí', 'departamento_id' => 21],
			['nombre' =>  'Providencia', 'departamento_id' => 21],
			['nombre' =>  'Puerres', 'departamento_id' => 21],
			['nombre' =>  'Pupiales', 'departamento_id' => 21],
			['nombre' =>  'Ricaurte', 'departamento_id' => 21],
			['nombre' =>  'Roberto Payán (San José)', 'departamento_id' => 21],
			['nombre' =>  'Samaniego', 'departamento_id' => 21],
			['nombre' =>  'San Bernardo', 'departamento_id' => 21],
			['nombre' =>  'San Juan de Pasto', 'departamento_id' => 21],
			['nombre' =>  'San Lorenzo', 'departamento_id' => 21],
			['nombre' =>  'San Pablo', 'departamento_id' => 21],
			['nombre' =>  'San Pedro de Cartago', 'departamento_id' => 21],
			['nombre' =>  'Sandoná', 'departamento_id' => 21],
			['nombre' =>  'Santa Bárbara (Iscuandé)', 'departamento_id' => 21],
			['nombre' =>  'Sapuyes', 'departamento_id' => 21],
			['nombre' =>  'Los Andes (Sotomayor)', 'departamento_id' => 21],
			['nombre' =>  'Taminango', 'departamento_id' => 21],
			['nombre' =>  'Tangua', 'departamento_id' => 21],
			['nombre' =>  'San Andrés de Tumaco', 'departamento_id' => 21],
			['nombre' =>  'Túquerres', 'departamento_id' => 21],
			['nombre' =>  'Yacuanquer', 'departamento_id' => 21],
			['nombre' =>  'Arboledas', 'departamento_id' => 22],
			['nombre' =>  'Bochalema', 'departamento_id' => 22],
			['nombre' =>  'Bucarasica', 'departamento_id' => 22],
			['nombre' =>  'Chinácota', 'departamento_id' => 22],
			['nombre' =>  'Chitagá', 'departamento_id' => 22],
			['nombre' =>  'Convención', 'departamento_id' => 22],
			['nombre' =>  'Cucutilla', 'departamento_id' => 22],
			['nombre' =>  'Cáchira', 'departamento_id' => 22],
			['nombre' =>  'Cácota', 'departamento_id' => 22],
			['nombre' =>  'Cúcuta', 'departamento_id' => 22],
			['nombre' =>  'Durania', 'departamento_id' => 22],
			['nombre' =>  'El Carmen', 'departamento_id' => 22],
			['nombre' =>  'El Tarra', 'departamento_id' => 22],
			['nombre' =>  'El Zulia', 'departamento_id' => 22],
			['nombre' =>  'Gramalote', 'departamento_id' => 22],
			['nombre' =>  'Hacarí', 'departamento_id' => 22],
			['nombre' =>  'Herrán', 'departamento_id' => 22],
			['nombre' =>  'La Esperanza', 'departamento_id' => 22],
			['nombre' =>  'La Playa', 'departamento_id' => 22],
			['nombre' =>  'Labateca', 'departamento_id' => 22],
			['nombre' =>  'Los Patios', 'departamento_id' => 22],
			['nombre' =>  'Lourdes', 'departamento_id' => 22],
			['nombre' =>  'Mutiscua', 'departamento_id' => 22],
			['nombre' =>  'Ocaña', 'departamento_id' => 22],
			['nombre' =>  'Pamplona', 'departamento_id' => 22],
			['nombre' =>  'Pamplonita', 'departamento_id' => 22],
			['nombre' =>  'Puerto Santander', 'departamento_id' => 22],
			['nombre' =>  'Ragonvalia', 'departamento_id' => 22],
			['nombre' =>  'Salazar', 'departamento_id' => 22],
			['nombre' =>  'San Calixto', 'departamento_id' => 22],
			['nombre' =>  'San Cayetano', 'departamento_id' => 22],
			['nombre' =>  'Santiago', 'departamento_id' => 22],
			['nombre' =>  'Sardinata', 'departamento_id' => 22],
			['nombre' =>  'Silos', 'departamento_id' => 22],
			['nombre' =>  'Teorama', 'departamento_id' => 22],
			['nombre' =>  'Tibú', 'departamento_id' => 22],
			['nombre' =>  'Toledo', 'departamento_id' => 22],
			['nombre' =>  'Villa Caro', 'departamento_id' => 22],
			['nombre' =>  'Villa del Rosario', 'departamento_id' => 22],
			['nombre' =>  'Ábrego', 'departamento_id' => 22],
			['nombre' =>  'Colón', 'departamento_id' => 23],
			['nombre' =>  'Mocoa', 'departamento_id' => 23],
			['nombre' =>  'Orito', 'departamento_id' => 23],
			['nombre' =>  'Puerto Asís', 'departamento_id' => 23],
			['nombre' =>  'Puerto Caicedo', 'departamento_id' => 23],
			['nombre' =>  'Puerto Guzmán', 'departamento_id' => 23],
			['nombre' =>  'Puerto Leguízamo', 'departamento_id' => 23],
			['nombre' =>  'San Francisco', 'departamento_id' => 23],
			['nombre' =>  'San Miguel', 'departamento_id' => 23],
			['nombre' =>  'Santiago', 'departamento_id' => 23],
			['nombre' =>  'Sibundoy', 'departamento_id' => 23],
			['nombre' =>  'Valle del Guamuez', 'departamento_id' => 23],
			['nombre' =>  'Villagarzón', 'departamento_id' => 23],
			['nombre' =>  'Armenia', 'departamento_id' => 24],
			['nombre' =>  'Buenavista', 'departamento_id' => 24],
			['nombre' =>  'Calarcá', 'departamento_id' => 24],
			['nombre' =>  'Circasia', 'departamento_id' => 24],
			['nombre' =>  'Cordobá', 'departamento_id' => 24],
			['nombre' =>  'Filandia', 'departamento_id' => 24],
			['nombre' =>  'Génova', 'departamento_id' => 24],
			['nombre' =>  'La Tebaida', 'departamento_id' => 24],
			['nombre' =>  'Montenegro', 'departamento_id' => 24],
			['nombre' =>  'Pijao', 'departamento_id' => 24],
			['nombre' =>  'Quimbaya', 'departamento_id' => 24],
			['nombre' =>  'Salento', 'departamento_id' => 24],
			['nombre' =>  'Apía', 'departamento_id' => 25],
			['nombre' =>  'Balboa', 'departamento_id' => 25],
			['nombre' =>  'Belén de Umbría', 'departamento_id' => 25],
			['nombre' =>  'Dos Quebradas', 'departamento_id' => 25],
			['nombre' =>  'Guática', 'departamento_id' => 25],
			['nombre' =>  'La Celia', 'departamento_id' => 25],
			['nombre' =>  'La Virginia', 'departamento_id' => 25],
			['nombre' =>  'Marsella', 'departamento_id' => 25],
			['nombre' =>  'Mistrató', 'departamento_id' => 25],
			['nombre' =>  'Pereira', 'departamento_id' => 25],
			['nombre' =>  'Pueblo Rico', 'departamento_id' => 25],
			['nombre' =>  'Quinchía', 'departamento_id' => 25],
			['nombre' =>  'Santa Rosa de Cabal', 'departamento_id' => 25],
			['nombre' =>  'Santuario', 'departamento_id' => 25],
			['nombre' =>  'Providencia', 'departamento_id' => 26],
			['nombre' =>  'Aguada', 'departamento_id' => 27],
			['nombre' =>  'Albania', 'departamento_id' => 27],
			['nombre' =>  'Aratoca', 'departamento_id' => 27],
			['nombre' =>  'Barbosa', 'departamento_id' => 27],
			['nombre' =>  'Barichara', 'departamento_id' => 27],
			['nombre' =>  'Barrancabermeja', 'departamento_id' => 27],
			['nombre' =>  'Betulia', 'departamento_id' => 27],
			['nombre' =>  'Bolívar', 'departamento_id' => 27],
			['nombre' =>  'Bucaramanga', 'departamento_id' => 27],
			['nombre' =>  'Cabrera', 'departamento_id' => 27],
			['nombre' =>  'California', 'departamento_id' => 27],
			['nombre' =>  'Capitanejo', 'departamento_id' => 27],
			['nombre' =>  'Carcasí', 'departamento_id' => 27],
			['nombre' =>  'Cepita', 'departamento_id' => 27],
			['nombre' =>  'Cerrito', 'departamento_id' => 27],
			['nombre' =>  'Charalá', 'departamento_id' => 27],
			['nombre' =>  'Charta', 'departamento_id' => 27],
			['nombre' =>  'Chima', 'departamento_id' => 27],
			['nombre' =>  'Chipatá', 'departamento_id' => 27],
			['nombre' =>  'Cimitarra', 'departamento_id' => 27],
			['nombre' =>  'Concepción', 'departamento_id' => 27],
			['nombre' =>  'Confines', 'departamento_id' => 27],
			['nombre' =>  'Contratación', 'departamento_id' => 27],
			['nombre' =>  'Coromoro', 'departamento_id' => 27],
			['nombre' =>  'Curití', 'departamento_id' => 27],
			['nombre' =>  'El Guacamayo', 'departamento_id' => 27],
			['nombre' =>  'El Peñon', 'departamento_id' => 27],
			['nombre' =>  'El Playón', 'departamento_id' => 27],
			['nombre' =>  'Encino', 'departamento_id' => 27],
			['nombre' =>  'Enciso', 'departamento_id' => 27],
			['nombre' =>  'Floridablanca', 'departamento_id' => 27],
			['nombre' =>  'Florián', 'departamento_id' => 27],
			['nombre' =>  'Galán', 'departamento_id' => 27],
			['nombre' =>  'Girón', 'departamento_id' => 27],
			['nombre' =>  'Guaca', 'departamento_id' => 27],
			['nombre' =>  'Guadalupe', 'departamento_id' => 27],
			['nombre' =>  'Guapota', 'departamento_id' => 27],
			['nombre' =>  'Guavatá', 'departamento_id' => 27],
			['nombre' =>  'Güepsa', 'departamento_id' => 27],
			['nombre' =>  'Gámbita', 'departamento_id' => 27],
			['nombre' =>  'Hato', 'departamento_id' => 27],
			['nombre' =>  'Jesús María', 'departamento_id' => 27],
			['nombre' =>  'Jordán', 'departamento_id' => 27],
			['nombre' =>  'La Belleza', 'departamento_id' => 27],
			['nombre' =>  'La Paz', 'departamento_id' => 27],
			['nombre' =>  'Landázuri', 'departamento_id' => 27],
			['nombre' =>  'Lebrija', 'departamento_id' => 27],
			['nombre' =>  'Los Santos', 'departamento_id' => 27],
			['nombre' =>  'Macaravita', 'departamento_id' => 27],
			['nombre' =>  'Matanza', 'departamento_id' => 27],
			['nombre' =>  'Mogotes', 'departamento_id' => 27],
			['nombre' =>  'Molagavita', 'departamento_id' => 27],
			['nombre' =>  'Málaga', 'departamento_id' => 27],
			['nombre' =>  'Ocamonte', 'departamento_id' => 27],
			['nombre' =>  'Oiba', 'departamento_id' => 27],
			['nombre' =>  'Onzaga', 'departamento_id' => 27],
			['nombre' =>  'Palmar', 'departamento_id' => 27],
			['nombre' =>  'Palmas del Socorro', 'departamento_id' => 27],
			['nombre' =>  'Pie de Cuesta', 'departamento_id' => 27],
			['nombre' =>  'Pinchote', 'departamento_id' => 27],
			['nombre' =>  'Puente Nacional', 'departamento_id' => 27],
			['nombre' =>  'Puerto Parra', 'departamento_id' => 27],
			['nombre' =>  'Puerto Wilches', 'departamento_id' => 27],
			['nombre' =>  'Páramo', 'departamento_id' => 27],
			['nombre' =>  'Rionegro', 'departamento_id' => 27],
			['nombre' =>  'Sabana de Torres', 'departamento_id' => 27],
			['nombre' =>  'San Andrés', 'departamento_id' => 27],
			['nombre' =>  'San Benito', 'departamento_id' => 27],
			['nombre' =>  'San Gíl', 'departamento_id' => 27],
			['nombre' =>  'San Joaquín', 'departamento_id' => 27],
			['nombre' =>  'San José de Miranda', 'departamento_id' => 27],
			['nombre' =>  'San Miguel', 'departamento_id' => 27],
			['nombre' =>  'San Vicente de Chucurí', 'departamento_id' => 27],
			['nombre' =>  'Santa Bárbara', 'departamento_id' => 27],
			['nombre' =>  'Santa Helena del Opón', 'departamento_id' => 27],
			['nombre' =>  'Simacota', 'departamento_id' => 27],
			['nombre' =>  'Socorro', 'departamento_id' => 27],
			['nombre' =>  'Suaita', 'departamento_id' => 27],
			['nombre' =>  'Sucre', 'departamento_id' => 27],
			['nombre' =>  'Suratá', 'departamento_id' => 27],
			['nombre' =>  'Tona', 'departamento_id' => 27],
			['nombre' =>  'Valle de San José', 'departamento_id' => 27],
			['nombre' =>  'Vetas', 'departamento_id' => 27],
			['nombre' =>  'Villanueva', 'departamento_id' => 27],
			['nombre' =>  'Vélez', 'departamento_id' => 27],
			['nombre' =>  'Zapatoca', 'departamento_id' => 27],
			['nombre' =>  'Buenavista', 'departamento_id' => 28],
			['nombre' =>  'Caimito', 'departamento_id' => 28],
			['nombre' =>  'Chalán', 'departamento_id' => 28],
			['nombre' =>  'Colosó (Ricaurte)', 'departamento_id' => 28],
			['nombre' =>  'Corozal', 'departamento_id' => 28],
			['nombre' =>  'Coveñas', 'departamento_id' => 28],
			['nombre' =>  'El Roble', 'departamento_id' => 28],
			['nombre' =>  'Galeras (Nueva Granada)', 'departamento_id' => 28],
			['nombre' =>  'Guaranda', 'departamento_id' => 28],
			['nombre' =>  'La Unión', 'departamento_id' => 28],
			['nombre' =>  'Los Palmitos', 'departamento_id' => 28],
			['nombre' =>  'Majagual', 'departamento_id' => 28],
			['nombre' =>  'Morroa', 'departamento_id' => 28],
			['nombre' =>  'Ovejas', 'departamento_id' => 28],
			['nombre' =>  'Palmito', 'departamento_id' => 28],
			['nombre' =>  'Sampués', 'departamento_id' => 28],
			['nombre' =>  'San Benito Abad', 'departamento_id' => 28],
			['nombre' =>  'San Juan de Betulia', 'departamento_id' => 28],
			['nombre' =>  'San Marcos', 'departamento_id' => 28],
			['nombre' =>  'San Onofre', 'departamento_id' => 28],
			['nombre' =>  'San Pedro', 'departamento_id' => 28],
			['nombre' =>  'Sincelejo', 'departamento_id' => 28],
			['nombre' =>  'San Luis de Sincé', 'departamento_id' => 28],
			['nombre' =>  'Sucre', 'departamento_id' => 28],
			['nombre' =>  'Santiago de Tolú', 'departamento_id' => 28],
			['nombre' =>  'Tolú Viejo', 'departamento_id' => 28],
			['nombre' =>  'Alpujarra', 'departamento_id' => 29],
			['nombre' =>  'Alvarado', 'departamento_id' => 29],
			['nombre' =>  'Ambalema', 'departamento_id' => 29],
			['nombre' =>  'Anzoátegui', 'departamento_id' => 29],
			['nombre' =>  'Armero (Guayabal)', 'departamento_id' => 29],
			['nombre' =>  'Ataco', 'departamento_id' => 29],
			['nombre' =>  'Cajamarca', 'departamento_id' => 29],
			['nombre' =>  'Carmen de Apicalá', 'departamento_id' => 29],
			['nombre' =>  'Casabianca', 'departamento_id' => 29],
			['nombre' =>  'Chaparral', 'departamento_id' => 29],
			['nombre' =>  'Coello', 'departamento_id' => 29],
			['nombre' =>  'Coyaima', 'departamento_id' => 29],
			['nombre' =>  'Cunday', 'departamento_id' => 29],
			['nombre' =>  'Dolores', 'departamento_id' => 29],
			['nombre' =>  'Espinal', 'departamento_id' => 29],
			['nombre' =>  'Falan', 'departamento_id' => 29],
			['nombre' =>  'Flandes', 'departamento_id' => 29],
			['nombre' =>  'Fresno', 'departamento_id' => 29],
			['nombre' =>  'Guamo', 'departamento_id' => 29],
			['nombre' =>  'Herveo', 'departamento_id' => 29],
			['nombre' =>  'Honda', 'departamento_id' => 29],
			['nombre' =>  'Ibagué', 'departamento_id' => 29],
			['nombre' =>  'Icononzo', 'departamento_id' => 29],
			['nombre' =>  'Lérida', 'departamento_id' => 29],
			['nombre' =>  'Líbano', 'departamento_id' => 29],
			['nombre' =>  'Mariquita', 'departamento_id' => 29],
			['nombre' =>  'Melgar', 'departamento_id' => 29],
			['nombre' =>  'Murillo', 'departamento_id' => 29],
			['nombre' =>  'Natagaima', 'departamento_id' => 29],
			['nombre' =>  'Ortega', 'departamento_id' => 29],
			['nombre' =>  'Palocabildo', 'departamento_id' => 29],
			['nombre' =>  'Piedras', 'departamento_id' => 29],
			['nombre' =>  'Planadas', 'departamento_id' => 29],
			['nombre' =>  'Prado', 'departamento_id' => 29],
			['nombre' =>  'Purificación', 'departamento_id' => 29],
			['nombre' =>  'Rioblanco', 'departamento_id' => 29],
			['nombre' =>  'Roncesvalles', 'departamento_id' => 29],
			['nombre' =>  'Rovira', 'departamento_id' => 29],
			['nombre' =>  'Saldaña', 'departamento_id' => 29],
			['nombre' =>  'San Antonio', 'departamento_id' => 29],
			['nombre' =>  'San Luis', 'departamento_id' => 29],
			['nombre' =>  'Santa Isabel', 'departamento_id' => 29],
			['nombre' =>  'Suárez', 'departamento_id' => 29],
			['nombre' =>  'Valle de San Juan', 'departamento_id' => 29],
			['nombre' =>  'Venadillo', 'departamento_id' => 29],
			['nombre' =>  'Villahermosa', 'departamento_id' => 29],
			['nombre' =>  'Villarrica', 'departamento_id' => 29],
			['nombre' =>  'Alcalá', 'departamento_id' => 30],
			['nombre' =>  'Andalucía', 'departamento_id' => 30],
			['nombre' =>  'Ansermanuevo', 'departamento_id' => 30],
			['nombre' =>  'Argelia', 'departamento_id' => 30],
			['nombre' =>  'Bolívar', 'departamento_id' => 30],
			['nombre' =>  'Buenaventura', 'departamento_id' => 30],
			['nombre' =>  'Guadalajara de Buga', 'departamento_id' => 30],
			['nombre' =>  'Bugalagrande', 'departamento_id' => 30],
			['nombre' =>  'Caicedonia', 'departamento_id' => 30],
			['nombre' =>  'Calima (Darién)', 'departamento_id' => 30],
			['nombre' =>  'Calí', 'departamento_id' => 30],
			['nombre' =>  'Candelaria', 'departamento_id' => 30],
			['nombre' =>  'Cartago', 'departamento_id' => 30],
			['nombre' =>  'Dagua', 'departamento_id' => 30],
			['nombre' =>  'El Cairo', 'departamento_id' => 30],
			['nombre' =>  'El Cerrito', 'departamento_id' => 30],
			['nombre' =>  'El Dovio', 'departamento_id' => 30],
			['nombre' =>  'El Águila', 'departamento_id' => 30],
			['nombre' =>  'Florida', 'departamento_id' => 30],
			['nombre' =>  'Ginebra', 'departamento_id' => 30],
			['nombre' =>  'Guacarí', 'departamento_id' => 30],
			['nombre' =>  'Jamundí', 'departamento_id' => 30],
			['nombre' =>  'La Cumbre', 'departamento_id' => 30],
			['nombre' =>  'La Unión', 'departamento_id' => 30],
			['nombre' =>  'La Victoria', 'departamento_id' => 30],
			['nombre' =>  'Obando', 'departamento_id' => 30],
			['nombre' =>  'Palmira', 'departamento_id' => 30],
			['nombre' =>  'Pradera', 'departamento_id' => 30],
			['nombre' =>  'Restrepo', 'departamento_id' => 30],
			['nombre' =>  'Riofrío', 'departamento_id' => 30],
			['nombre' =>  'Roldanillo', 'departamento_id' => 30],
			['nombre' =>  'San Pedro', 'departamento_id' => 30],
			['nombre' =>  'Sevilla', 'departamento_id' => 30],
			['nombre' =>  'Toro', 'departamento_id' => 30],
			['nombre' =>  'Trujillo', 'departamento_id' => 30],
			['nombre' =>  'Tulúa', 'departamento_id' => 30],
			['nombre' =>  'Ulloa', 'departamento_id' => 30],
			['nombre' =>  'Versalles', 'departamento_id' => 30],
			['nombre' =>  'Vijes', 'departamento_id' => 30],
			['nombre' =>  'Yotoco', 'departamento_id' => 30],
			['nombre' =>  'Yumbo', 'departamento_id' => 30],
			['nombre' =>  'Zarzal', 'departamento_id' => 30],
			['nombre' =>  'Carurú', 'departamento_id' => 31],
			['nombre' =>  'Mitú', 'departamento_id' => 31],
			['nombre' =>  'Taraira', 'departamento_id' => 31],
			['nombre' =>  'Cumaribo', 'departamento_id' => 32],
			['nombre' =>  'La Primavera', 'departamento_id' => 32],
			['nombre' =>  'Puerto Carreño', 'departamento_id' => 32],
			['nombre' =>  'Santa Rosalía', 'departamento_id' => 32],
			['nombre' =>  'Barranco Minas', 'departamento_id' => 15],
			['nombre' =>  'Cacahual', 'departamento_id' => 15],
			['nombre' =>  'La Guadalupe', 'departamento_id' => 15],
			['nombre' =>  'Mapiripana', 'departamento_id' => 15],
			['nombre' =>  'Morichal', 'departamento_id' => 15],
			['nombre' =>  'Pana Pana', 'departamento_id' => 15],
			['nombre' =>  'Puerto Colombia', 'departamento_id' => 15],
			['nombre' =>  'San Felipe', 'departamento_id' => 15],
			['nombre' =>  'El Encanto', 'departamento_id' => 1],
			['nombre' =>  'La Chorrera', 'departamento_id' => 1],
			['nombre' =>  'La Pedrera', 'departamento_id' => 1],
			['nombre' =>  'La Victoria', 'departamento_id' => 1],
			['nombre' =>  'Mirití-Paraná', 'departamento_id' => 1],
			['nombre' =>  'Puerto Alegria', 'departamento_id' => 1],
			['nombre' =>  'Puerto Arica', 'departamento_id' => 1],
			['nombre' =>  'Puerto Santander', 'departamento_id' => 1],
			['nombre' =>  'Tarapacá', 'departamento_id' => 1],
			['nombre' =>  'El Carmen de Chucurí', 'departamento_id' => 27],
			['nombre' =>  'El Litoral de San Juan', 'departamento_id' => 12],
			['nombre' =>  'Pacoa', 'departamento_id' => 31],
			['nombre' =>  'Papunaua', 'departamento_id' => 31],
			['nombre' =>  'Yavaraté', 'departamento_id' => 31],
			['nombre' =>  'San Andrés', 'departamento_id' => 26],
			['nombre' =>  'Santacruz', 'departamento_id' => 21]
        ]);
    }
}